# Every service that needs to be running in hub.
version: '3.8'

services:

  static:

    image: "nginx:1.22"

    deploy:
      endpoint_mode: dnsrr
      replicas: 3
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
      restart_policy:
        condition: on-failure

