FROM schtr4jh/pckg:base-alpine
MAINTAINER schtr4jh@schtr4jh.net
COPY utils /usr/local/pckg-utils/
RUN apk add --repository http://dl-cdn.alpinelinux.org/alpine/edge/community \
	&& date \
	&& curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash - \
	&& curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
	&& echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
	&& apk update \
	&& apk add mysql-client apache2 libapache2-mod-fcgid php7.4 php7.4-fpm php7.4-curl php7.4-intl php7.4-xml php7.4-mbstring php7.4-zip php7.4-mysql php7.4-cli php-amqplib php7.4-ssh2 php7.4-zmq php7.4-imap php7.4-redis php7.4-bcmath php7.4-gd php7.4-bz2 php7.4-soap php7.4-dev wget xvfb git zip unzip g++ build-essential nodejs yarn python2 \
	&& cp /usr/local/pckg-utils/external/etc_apache2_apache2-fpm.conf /etc/apache2/apache2.conf \
	&& cp /usr/local/pckg-utils/external/000-default-fpm.conf /etc/apache2/sites-enabled/000-default.conf \
	&& mkdir -p /etc/ssl/private/ \
	&& cp /usr/local/pckg-utils/external/apache-selfsigned.crt /etc/ssl/certs/apache-selfsigned.crt \
	&& cp /usr/local/pckg-utils/external/apache-selfsigned.key /etc/ssl/private/apache-selfsigned.key \
	&& a2enmod expires headers rewrite ssl proxy_fcgi \
	&& a2enconf php7.4-fpm \
	&& php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
	&& php -r "if (hash_file('sha384', 'composer-setup.php') === 'dac665fdc30fdd8ec78b38b9800061b4150413ff2e3b6f88543c636f7cd84f6db9189d43a81e5503cda447da73c7e5b6') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
	&& php composer-setup.php \
	&& php -r "unlink('composer-setup.php');" \
	&& mv composer.phar /usr/local/bin/composer \
	&& npm install -g npm@8 less webpack@5 webpack-cli@4 \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /usr/local/pckg-utils
WORKDIR /var/www/html/
COPY docker-entrypoint-apache-fpm.sh /
ENTRYPOINT ["sh", "/docker-entrypoint-apache-fpm.sh"]