FROM schtr4jh/pckg:base
MAINTAINER schtr4jh@schtr4jh.net
COPY utils /usr/local/pckg-utils/
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - \
	&& add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
	&& apt-get -y update \
	&& apt-get install -y docker-ce docker-ce-cli containerd.io \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /usr/local/pckg-utils
WORKDIR /var/www/html/
COPY docker-entrypoint-docker.sh /
ENTRYPOINT ["sh", "/docker-entrypoint-docker.sh"]