FROM schtr4jh/pckg:base
MAINTAINER schtr4jh@schtr4jh.net

# worker = php + apache + mysql
RUN sh /usr/local/pckg-utils/installWeb.sh

# copy apache config
RUN sh /usr/local/pckg-utils/configApache.sh

# composer + node + npm + yarn + less + webpack
RUN sh /usr/local/pckg-utils/installFrontend.sh

# cleanup
RUN rm -rf /var/lib/apt/lists/* /usr/local/pckg-utils

# open ports
# EXPOSE 80 443

# entrypoint
COPY docker-entrypoint-apache.sh /
ENTRYPOINT ["sh", "/docker-entrypoint-apache.sh"]