FROM schtr4jh/pckg:base
MAINTAINER schtr4jh@schtr4jh.net

# install redis
RUN sh /usr/local/pckg-utils/installRedis.sh

# config redis
RUN sh /usr/local/pckg-utils/configRedis.sh

# cleanup
RUN rm -rf /var/lib/apt/lists/* /usr/local/pckg-utils

# open ports
# EXPOSE 80 443

# entrypoint
COPY docker-entrypoint-redis.sh /
ENTRYPOINT ["sh", "/docker-entrypoint-redis.sh"]