FROM schtr4jh/pckg:php-go
MAINTAINER schtr4jh@schtr4jh.net

# add utils so we can optimize a few things
RUN cp -R utils /usr/local/pckg-utils

# supervisord
RUN apt-get update && apt-get install -y supervisor

# change workdir for a developer
WORKDIR /var/www/html/

COPY docker-entrypoint-php-go-supervisord.sh /
ENTRYPOINT ["sh", "/docker-entrypoint-php-go-supervisord.sh"]
