FROM ubuntu:groovy-20210325
MAINTAINER schtr4jh@schtr4jh.net

RUN wget https://github.com/ethersphere/bee-clef/releases/download/v0.4.1/bee-clef_0.4.1_amd64.deb
RUN sudo dpkg -i bee-clef_0.4.1_amd64.deb

RUN wget https://github.com/ethersphere/bee/releases/download/v0.4.1/bee_0.4.1_amd64.deb
RUN sudo dpkg -i bee_0.4.1_amd64.deb

# /etc/bee-clef/
# /var/lib/bee-clef/

# entrypoint
COPY docker-entrypoint-bee.sh /
ENTRYPOINT ["sh", "/docker-entrypoint-bee.sh"]