FROM schtr4jh/pckg:base
MAINTAINER schtr4jh@schtr4jh.net

# add utils so we can optimize a few things
RUN cp -R utils /usr/local/pckg-utils

# install redis
RUN sh /usr/local/pckg-utils/installBeanstalkd.sh

# config redis
RUN sh /usr/local/pckg-utils/configBeanstalkd.sh

# entrypoint
COPY docker-entrypoint-beanstalkd.sh /
ENTRYPOINT ["sh", "/docker-entrypoint-beanstalkd.sh"]