FROM ubuntu:20.04
MAINTAINER schtr4jh@schtr4jh.net
COPY utils /usr/local/pckg-utils/
RUN apt-get update \
	&& apt-get install -y locales software-properties-common sudo curl apt-transport-https tzdata openssl \
	&& locale-gen en_US.UTF-8 \
	&& echo Europe/Ljubljana > /etc/timezone \
	&& dpkg-reconfigure -f noninteractive tzdata \
	&& add-apt-repository ppa:ondrej/php \
	&& apt-get update \
	&& apt-get install -y apache2 libapache2-mod-php php7.4 php-curl php-intl php-xml php-mbstring php-zip php-mysql php-cli php-amqplib php-ssh2 php-zmq php-imap php-redis php-bcmath php-gd php-bz2 php-soap wget xvfb git zip unzip mysql-client \
	&& cp /usr/local/pckg-utils/external/etc_apache2_apache2.conf /etc/apache2/apache2.conf \
	&& cp /usr/local/pckg-utils/external/000-default.conf /etc/apache2/sites-enabled/000-default.conf \
	&& mkdir -p /etc/ssl/private/ \
	&& cp /usr/local/pckg-utils/external/apache-selfsigned.crt /etc/ssl/certs/apache-selfsigned.crt \
	&& cp /usr/local/pckg-utils/external/apache-selfsigned.key /etc/ssl/private/apache-selfsigned.key \
	&& a2enmod expires headers rewrite ssl \
	&& sh /usr/local/pckg-utils/installComposer.sh \
	&& sh /usr/local/pckg-utils/installNode.sh \
	&& sh /usr/local/pckg-utils/installYarn.sh \
	&& sh /usr/local/pckg-utils/installLess.sh \
	&& sh /usr/local/pckg-utils/installWebpack.sh \
	&& rm -rf /var/lib/apt/lists/* /usr/local/pckg-utils
# EXPOSE 80 443
COPY docker-entrypoint-apache.sh /
ENTRYPOINT ["sh", "/docker-entrypoint-apache.sh"]