FROM ubuntu:20.04
MAINTAINER schtr4jh@schtr4jh.net

# add utils so we can optimize a few things
COPY utils /usr/local/pckg-utils/

# Update system, install common
RUN sh /usr/local/pckg-utils/initialUpdate.sh

# entrypoint
ENTRYPOINT ["date"]