FROM ubuntu:18.04
MAINTAINER schtr4jh@schtr4jh.net

# add utils so we can optimize a few things
COPY utils /usr/local/pckg-utils/

# Update system, install common
RUN sh /usr/local/pckg-utils/initialUpdate.sh

# worker = php + mysql client
RUN sh /usr/local/pckg-utils/installWeb-cron.sh

# cleanup
RUN rm -rf /var/lib/apt/lists/* /usr/local/pckg-utils

# entrypoint
COPY docker-entrypoint-php-cron.sh /
ENTRYPOINT ["sh", "/docker-entrypoint-php-cron.sh"]