FROM schtr4jh/pckg:base
MAINTAINER schtr4jh@schtr4jh.net

# install redis
RUN sh /usr/local/pckg-utils/installBeanstalkd.sh

# config redis
RUN sh /usr/local/pckg-utils/configBeanstalkd.sh

# cleanup
RUN rm -rf /var/lib/apt/lists/* /usr/local/pckg-utils

# open ports
# EXPOSE 11300

# entrypoint
COPY docker-entrypoint-beanstalkd.sh /
ENTRYPOINT ["sh", "/docker-entrypoint-beanstalkd.sh"]