FROM schtr4jh/pckg:base
MAINTAINER schtr4jh@schtr4jh.net

# node + npm + yarn + less + webpack
RUN sh /usr/local/pckg-utils/installBasicFrontend.sh

# create dev user
RUN sh /usr/local/pckg-utils/addDeveloper.sh

# change workdir for a developer
# USER developer
WORKDIR /var/www/html/

# install hub requirements
COPY commsdev/hub-dev /usr/local/commsdev-utils
RUN sh /usr/local/commsdev-utils/installHub.sh

# cleanup
#RUN rm -rf /var/lib/apt/lists/* /usr/local/pckg-utils /usr/local/commsdev-utils

# change workdir for a developer
WORKDIR /var/www/html/

# entrypoint
COPY docker-entrypoint-commsdev-hub-dev.sh /
ENTRYPOINT ["sh", "/docker-entrypoint-commsdev-hub-dev.sh"]