FROM schtr4jh/pckg:base
MAINTAINER schtr4jh@schtr4jh.net
RUN cp -R utils /usr/local/pckg-utils \
	&& sudo apt-get install -y redis-server \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /usr/local/pckg-utils
COPY docker-entrypoint-redis.sh /
ENTRYPOINT ["sh", "/docker-entrypoint-redis.sh"]