FROM schtr4jh/pckg:base
MAINTAINER schtr4jh@schtr4jh.net
COPY utils /usr/local/pckg-utils/
RUN add-apt-repository ppa:ondrej/php \
	&& apt-get update \
	&& apt-get install -y mysql-client php7.4 php-curl php-intl php-xml php-mbstring php-zip php-mysql php-cli php-amqplib php-ssh2 php-zmq php-imap php-redis php-bcmath php-gd php-bz2 php-soap wget xvfb zip unzip \
	&& apt-get install -q -y rsyslog \
	&& sudo apt-get install -y sendmail opendkim opendkim-tools \
	&& mkdir /etc/opendkim \
	&& mkdir /etc/opendkim/keys \
	&& touch /etc/opendkim/KeyTable \
	&& touch /etc/opendkim/SigningTable \
	&& touch /etc/opendkim/TrustedHosts \
	&& cp /usr/local/pckg-utils/external/etc_opendkim.conf /etc/opendkim.conf \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /usr/local/pckg-utils
WORKDIR /var/www/html/
COPY docker-entrypoint-sendmail-php.sh /
ENTRYPOINT ["sh", "/docker-entrypoint-sendmail-php.sh"]