FROM schtr4jh/pckg:base-alpine
MAINTAINER schtr4jh@schtr4jh.net
COPY utils /usr/local/pckg-utils/
RUN apk add --repository http://dl-cdn.alpinelinux.org/alpine/edge/community \
	&& date \
	&& curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash - \
	&& curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
	&& echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
	&& apk update \
	&& apk add mysql-client postgresql-client apache2 libapache2-mod-fcgid php8.0 php8.0-fpm php8.0-curl php8.0-intl php8.0-xml php8.0-mbstring php8.0-zip php8.0-mysql php8.0-pgsql php8.0-cli php8.0-amqplib php8.0-ssh2 php8.0-zmq php8.0-imap php8.0-redis php8.0-bcmath php8.0-gd php8.0-bz2 php8.0-soap php8.0-dev wget xvfb git zip unzip g++ build-essential nodejs yarn python2 \
	&& cp /usr/local/pckg-utils/external/etc_apache2_apache2-fpm.conf /etc/apache2/apache2.conf \
	&& cp /usr/local/pckg-utils/external/000-default-fpm-80.conf /etc/apache2/sites-enabled/000-default.conf \
	&& mkdir -p /etc/ssl/private/ \
	&& cp /usr/local/pckg-utils/external/apache-selfsigned.crt /etc/ssl/certs/apache-selfsigned.crt \
	&& cp /usr/local/pckg-utils/external/apache-selfsigned.key /etc/ssl/private/apache-selfsigned.key \
	&& a2enmod expires headers rewrite ssl proxy_fcgi \
	&& a2enconf php8.0-fpm \
	&& php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
	&& php -r "if (hash_file('sha384', 'composer-setup.php') === '906a84df04cea2aa72f40b5f787e49f22d4c2f19492ac310e8cba5b96ac8b64115ac402c8cd292b8a03482574915d1a8') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
	&& php composer-setup.php \
	&& php -r "unlink('composer-setup.php');" \
	&& mv composer.phar /usr/local/bin/composer \
	&& npm install -g npm@6 less webpack webpack-cli \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /usr/local/pckg-utils
WORKDIR /var/www/html/
COPY docker-entrypoint-apache-fpm-80.sh /
ENTRYPOINT ["sh", "/docker-entrypoint-apache-fpm-80.sh"]
