FROM schtr4jh/pckg:base-alpine
MAINTAINER schtr4jh@schtr4jh.net
COPY utils /usr/local/pckg-utils/
RUN apk update \
	&& apk add rabbitmq-server \
	&& cp /usr/local/pckg-utils/external/rabbitmq-server /etc/default/rabbitmq-server \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /usr/local/pckg-utils
COPY docker-entrypoint-rabbitmq.sh /
ENTRYPOINT ["sh", "/docker-entrypoint-rabbitmq.sh"]