FROM ubuntu:18.04
MAINTAINER schtr4jh@schtr4jh.net

# add utils so we can optimize a few things
COPY utils /usr/local/pckg-utils/

# Update system, install common
RUN sh /usr/local/pckg-utils/initialUpdate.sh

# install rabbitmq
RUN sh /usr/local/pckg-utils/installRabbitMQ.sh

# config rabbitmq
RUN sh /usr/local/pckg-utils/installRabbitMQ.sh

# cleanup
RUN rm -rf /var/lib/apt/lists/* /usr/local/pckg-utils

# open ports
# EXPOSE 80 443

# entrypoint
COPY docker-entrypoint-rabbitmq.sh /
ENTRYPOINT ["sh", "/docker-entrypoint-rabbitmq.sh"]