FROM schtr4jh/pckg:base-alpine
MAINTAINER schtr4jh@schtr4jh.net
COPY utils /usr/local/pckg-utils/
RUN apk add --repository http://dl-cdn.alpinelinux.org/alpine/edge/community \
	&& apk update \
	&& apk add mysql-client postgresql-client php7.4 php7.4-curl php7.4-intl php7.4-xml php7.4-mbstring php7.4-zip php7.4-mysql php7.4-pgsql php7.4-cli php-amqplib php7.4-ssh2 php7.4-zmq php7.4-imap php7.4-redis php7.4-bcmath php7.4-gd php7.4-bz2 php7.4-soap php7.4-dev wget xvfb git zip unzip cron rsyslog -q sendmail opendkim opendkim-tools \
	&& sudo update-alternatives --set php /usr/bin/php7.4 \
	&& mkdir /etc/opendkim \
	&& mkdir /etc/opendkim/keys \
	&& touch /etc/opendkim/KeyTable \
	&& touch /etc/opendkim/SigningTable \
	&& touch /etc/opendkim/TrustedHosts \
	&& cp /usr/local/pckg-utils/external/etc_opendkim.conf /etc/opendkim.conf \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /usr/local/pckg-utils
WORKDIR /var/www/html/
COPY docker-entrypoint-sendmail-php.sh /
ENTRYPOINT ["sh", "/docker-entrypoint-sendmail-php.sh"]