FROM schtr4jh/pckg:base
MAINTAINER schtr4jh@schtr4jh.net

# Install docker
RUN sh /usr/local/pckg-utils/installDocker.sh

# change workdir for a developer
# USER developer
WORKDIR /var/www/html/

# cleanup
RUN rm -rf /var/lib/apt/lists/* /usr/local/pckg-utils

# entrypoint
COPY docker-entrypoint-docker.sh /
ENTRYPOINT ["sh", "/docker-entrypoint-docker.sh"]