FROM schtr4jh/pckg:base
MAINTAINER schtr4jh@schtr4jh.net

# install rabbitmq
RUN sh /usr/local/pckg-utils/installRabbitMQ.sh

# config rabbitmq
RUN sh /usr/local/pckg-utils/configRabbitMQ.sh

# cleanup
RUN rm -rf /var/lib/apt/lists/* /usr/local/pckg-utils

# open ports
# EXPOSE 80 443

# entrypoint
COPY docker-entrypoint-rabbitmq.sh /
ENTRYPOINT ["sh", "/docker-entrypoint-rabbitmq.sh"]