FROM alpine:3.15
MAINTAINER schtr4jh@schtr4jh.net
RUN apk update \
	&& apk add sudo curl tzdata openssl ca-certificates \
	&& date \
	&& echo Europe/Ljubljana > /etc/timezone \
	&& date \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /usr/local/pckg-utils
ENTRYPOINT ["date"]