FROM schtr4jh/pckg:base-alpine
MAINTAINER schtr4jh@schtr4jh.net
COPY utils /usr/local/pckg-utils/
RUN apk add --repository http://dl-cdn.alpinelinux.org/alpine/edge/community \
	&& date \
	&& curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash - \
	&& curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
	&& echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
	&& apk update \
	&& apk add mysql-client apache2 libapache2-mod-fcgid php8.3 php8.3-fpm php8.3-curl php8.3-intl php8.3-xml php8.3-mbstring php8.3-zip php8.3-mysql php8.3-cli php-amqplib php8.3-ssh2 php8.3-zmq php8.3-imap php8.3-redis php8.3-bcmath php8.3-gd php8.3-bz2 php8.3-soap php8.3-dev wget xvfb git zip unzip g++ build-essential nodejs yarn python2 \
	&& cp /usr/local/pckg-utils/external/etc_apache2_apache2-fpm.conf /etc/apache2/apache2.conf \
	&& cp /usr/local/pckg-utils/external/000-default-fpm-83.conf /etc/apache2/sites-enabled/000-default.conf \
	&& mkdir -p /etc/ssl/private/ \
	&& cp /usr/local/pckg-utils/external/apache-selfsigned.crt /etc/ssl/certs/apache-selfsigned.crt \
	&& cp /usr/local/pckg-utils/external/apache-selfsigned.key /etc/ssl/private/apache-selfsigned.key \
	&& a2enmod expires headers rewrite ssl proxy_fcgi \
	&& a2enconf php8.3-fpm \
	&& php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
	&& php -r "if (hash_file('sha384', 'composer-setup.php') === 'edb40769019ccf227279e3bdd1f5b2e9950eb000c3233ee85148944e555d97be3ea4f40c3c2fe73b22f875385f6a5155') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
	&& php composer-setup.php \
	&& php -r "unlink('composer-setup.php');" \
	&& mv composer.phar /usr/local/bin/composer \
	&& npm install -g npm@8 less webpack@5 webpack-cli@4 \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /usr/local/pckg-utils
WORKDIR /var/www/html/
COPY docker-entrypoint-apache-fpm-83.sh /
ENTRYPOINT ["sh", "/docker-entrypoint-apache-fpm-83.sh"]