FROM schtr4jh/pckg:base
MAINTAINER schtr4jh@schtr4jh.net

# add utils so we can optimize a few things
RUN cp -R utils /usr/local/pckg-utils

# worker = php + mysql client
RUN sh /usr/local/pckg-utils/installWeb-cron.sh

# go
RUN apt-get install golang golang-go -y

RUN export GOPATH=/var/www/html
RUN export GOBIN=$GOPATH/bin
RUN PATH=$PATH:$GOPATH:$GOBIN
RUN export PATH

# change workdir for a developer
WORKDIR /var/www/html/

# entrypoint
COPY docker-entrypoint-php-go.sh /
ENTRYPOINT ["sh", "/docker-entrypoint-php-go.sh"]