FROM ubuntu:20.04
MAINTAINER schtr4jh@schtr4jh.net

# add utils so we can optimize a few things
COPY utils /usr/local/pckg-utils/

# Update system, install common
RUN sh /usr/local/pckg-utils/initialUpdate.sh

# Install docker
RUN sh /usr/local/pckg-utils/installDocker.sh

# change workdir for a developer
# USER developer
WORKDIR /var/www/html/

# cleanup
RUN rm -rf /var/lib/apt/lists/* /usr/local/pckg-utils

# entrypoint
COPY docker-entrypoint-docker.sh /
ENTRYPOINT ["sh", "/docker-entrypoint-docker.sh"]