FROM ubuntu:groovy-20210325
MAINTAINER schtr4jh@schtr4jh.net
RUN apt-get -y update \
	&& apt-get install -y locales software-properties-common sudo curl apt-transport-https apt-utils tzdata openssl ca-certificates gnupg-agent \
	&& locale-gen en_US.UTF-8 \
	&& echo Europe/Ljubljana > /etc/timezone \
	&& dpkg-reconfigure -f noninteractive tzdata \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /usr/local/pckg-utils
ENTRYPOINT ["date"]