FROM schtr4jh/pckg:base
MAINTAINER schtr4jh@schtr4jh.net

# add utils so we can optimize a few things
RUN cp -R utils /usr/local/pckg-utils

# worker = php + mysql client
RUN sh /usr/local/pckg-utils/installWeb-cron.sh

# change workdir for a developer
WORKDIR /var/www/html/

# entrypoint
COPY docker-entrypoint-php-cron.sh /
ENTRYPOINT ["sh", "/docker-entrypoint-php-cron.sh"]