FROM schtr4jh/pckg:base
MAINTAINER schtr4jh@schtr4jh.net

# add utils so we can optimize a few things
COPY utils /usr/local/pckg-utils/
#RUN cp -R utils /usr/local/pckg-utils

# worker = php + apache + mysql
RUN sh /usr/local/pckg-utils/installWeb.sh

# copy apache config
RUN sh /usr/local/pckg-utils/configApache.sh

# composer + node + npm + yarn + less + webpack
RUN sh /usr/local/pckg-utils/installFrontend.sh

# change workdir for a developer
WORKDIR /var/www/html/

# entrypoint
COPY docker-entrypoint-apache.sh /
ENTRYPOINT ["sh", "/docker-entrypoint-apache.sh"]