FROM schtr4jh/pckg:base-alpine
MAINTAINER schtr4jh@schtr4jh.net
COPY utils /usr/local/pckg-utils/
RUN sudo apk update \
	&& sudo apk add redis-server \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /usr/local/pckg-utils
COPY docker-entrypoint-redis.sh /
ENTRYPOINT ["sh", "/docker-entrypoint-redis.sh"]