FROM schtr4jh/pckg:base
MAINTAINER schtr4jh@schtr4jh.net

# worker = php + mysql client
RUN sh /usr/local/pckg-utils/installWeb-cron.sh

#
RUN apt-get install -q -y rsyslog

# worker = sendmail + opendkim
RUN sh /usr/local/pckg-utils/installSendmail.sh

# configure sendmail + opendkim
RUN sh /usr/local/pckg-utils/configSendmail.sh

# cleanup
RUN rm -rf /var/lib/apt/lists/*

# change workdir for a developer
WORKDIR /var/www/html/

# entrypoint
COPY docker-entrypoint-sendmail-php.sh /
ENTRYPOINT ["sh", "/docker-entrypoint-sendmail-php.sh"]