FROM ubuntu:18.04
MAINTAINER schtr4jh@schtr4jh.net
COPY utils /usr/local/pckg-utils/
RUN apt-get update \
	&& apt-get install -y locales software-properties-common sudo curl apt-transport-https tzdata openssl \
	&& locale-gen en_US.UTF-8 \
	&& echo Europe/Ljubljana > /etc/timezone \
	&& dpkg-reconfigure -f noninteractive tzdata \
	&& add-apt-repository ppa:ondrej/php \
	&& apt-get update \
	&& apt-get install -y mysql-client php7.4 php-curl php-intl php-xml php-mbstring php-zip php-mysql php-cli php-amqplib php-ssh2 php-zmq php-imap php-redis php-bcmath php-gd php-bz2 php-soap wget xvfb zip unzip \
	&& apt-get install golang golang-go -y \
	&& rm -rf /var/lib/apt/lists/* /usr/local/pckg-utils \
	&& export GOPATH=/var/www/html \
	&& export GOBIN=$GOPATH/bin \
	&& PATH=$PATH:$GOPATH:$GOBIN \
	&& export PATH
COPY docker-entrypoint-php-go.sh /
ENTRYPOINT ["sh", "/docker-entrypoint-php-go.sh"]