FROM schtr4jh/pckg:base
MAINTAINER schtr4jh@schtr4jh.net

# add utils so we can optimize a few things
COPY utils /usr/local/pckg-utils/
#RUN cp -R utils /usr/local/pckg-utils

# worker = php + mysql client
RUN sh /usr/local/pckg-utils/installWeb-cron.sh

#
RUN apt-get install -q -y rsyslog

# worker = sendmail + opendkim
RUN sh /usr/local/pckg-utils/installSendmail.sh

# configure sendmail + opendkim
RUN sh /usr/local/pckg-utils/configSendmail.sh

# change workdir for a developer
WORKDIR /var/www/html/

# entrypoint
COPY docker-entrypoint-sendmail-php.sh /
ENTRYPOINT ["sh", "/docker-entrypoint-sendmail-php.sh"]