FROM schtr4jh/pckg:base
MAINTAINER schtr4jh@schtr4jh.net

# add utils so we can optimize a few things
RUN cp -R utils /usr/local/pckg-utils

# install rabbitmq
RUN sh /usr/local/pckg-utils/installRabbitMQ.sh

# config rabbitmq
RUN sh /usr/local/pckg-utils/configRabbitMQ.sh

# entrypoint
COPY docker-entrypoint-rabbitmq.sh /
ENTRYPOINT ["sh", "/docker-entrypoint-rabbitmq.sh"]