FROM ubuntu:20.04
MAINTAINER schtr4jh@schtr4jh.net

# add utils so we can optimize a few things
COPY utils /usr/local/pckg-utils/

# Update system, install common
RUN sh /usr/local/pckg-utils/initialUpdate.sh

# install redis
RUN sh /usr/local/pckg-utils/installRedis.sh

# config redis
RUN sh /usr/local/pckg-utils/configRedis.sh

# cleanup
RUN rm -rf /var/lib/apt/lists/* /usr/local/pckg-utils

# open ports
# EXPOSE 80 443

# entrypoint
COPY docker-entrypoint-redis.sh /
ENTRYPOINT ["sh", "/docker-entrypoint-redis.sh"]