FROM schtr4jh/pckg:base
MAINTAINER schtr4jh@schtr4jh.net
COPY utils /usr/local/pckg-utils/
RUN add-apt-repository ppa:ondrej/php \
	&& add-apt-repository ppa:ondrej/apache2 \
	&& curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash - \
	&& curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
	&& echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
	&& apt-get -y update \
	&& apt-get install -y mysql-client apache2 libapache2-mod-fcgid php8.0 php8.0-fpm php8.0-curl php8.0-intl php8.0-xml php8.0-mbstring php8.0-zip php8.0-mysql php8.0-cli php-amqplib php8.0-ssh2 php8.0-zmq php8.0-imap php8.0-redis php8.0-bcmath php8.0-gd php8.0-bz2 php8.0-soap php8.0-dev wget xvfb git zip unzip g++ build-essential nodejs yarn python2 \
	&& update-alternatives --set php /usr/bin/php8.0 \
	&& cp /usr/local/pckg-utils/external/etc_apache2_apache2-fpm.conf /etc/apache2/apache2.conf \
	&& cp /usr/local/pckg-utils/external/000-default-fpm-80.conf /etc/apache2/sites-enabled/000-default.conf \
	&& cp /usr/local/pckg-utils/external/000-default-fpm-80-http.conf /etc/apache2/sites-available/000-default-http.conf \
	&& mkdir -p /etc/ssl/private/ \
	&& cp /usr/local/pckg-utils/external/apache-selfsigned.crt /etc/ssl/certs/apache-selfsigned.crt \
	&& cp /usr/local/pckg-utils/external/apache-selfsigned.key /etc/ssl/private/apache-selfsigned.key \
	&& a2enmod expires headers rewrite ssl proxy_fcgi \
	&& a2enconf php8.0-fpm \
	&& php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
	&& php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
	&& php composer-setup.php \
	&& php -r "unlink('composer-setup.php');" \
	&& mv composer.phar /usr/local/bin/composer \
	&& npm install -g npm@6 less webpack@5 webpack-cli@4 \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /usr/local/pckg-utils
WORKDIR /var/www/html/
COPY docker-entrypoint-apache-fpm-80.sh /
ENTRYPOINT ["sh", "/docker-entrypoint-apache-fpm-80.sh"]