FROM schtr4jh/pckg:base-alpine
MAINTAINER schtr4jh@schtr4jh.net
COPY utils /usr/local/pckg-utils/
RUN apk add --repository http://dl-cdn.alpinelinux.org/alpine/edge/community \
	&& date \
	&& curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - \
	&& curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
	&& echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
	&& apk update \
	&& apk add lsyncd redis-server rabbitmq-server mysql-server mysql-client postgresql-client apache2 libapache2-mod-php php7.4 php7.4-curl php7.4-intl php7.4-xml php7.4-mbstring php7.4-zip php7.4-mysql php7.4-pgsql php7.4-cli php-amqplib php-ssh2 php7.4-zmq php7.4-imap php7.4-redis php7.4-bcmath php7.4-gd php7.4-bz2 php7.4-soap php7.4-dev wget xvfb git zip unzip g++ build-essential nodejs yarn python2 iputils-ping nano net-tools zsh openvpn gcc make \
	&& sudo update-alternatives --set php /usr/bin/php7.4 \
	&& cp /usr/local/pckg-utils/external/etc_apache2_apache2.conf /etc/apache2/apache2.conf \
	&& cp /usr/local/pckg-utils/external/000-default.conf /etc/apache2/sites-enabled/000-default.conf \
	&& mkdir -p /etc/ssl/private/ \
	&& cp /usr/local/pckg-utils/external/apache-selfsigned.crt /etc/ssl/certs/apache-selfsigned.crt \
	&& cp /usr/local/pckg-utils/external/apache-selfsigned.key /etc/ssl/private/apache-selfsigned.key \
	&& a2dismod php8.0 \
	&& a2enmod expires headers rewrite ssl \
	&& php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
	&& php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
	&& php composer-setup.php \
	&& php -r "unlink('composer-setup.php');" \
	&& mv composer.phar /usr/local/bin/composer \
	&& npm install -g npm@6 less webpack webpack-cli \
	&& wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh || true \
	&& useradd -ms /bin/bash developer \
	&& adduser developer sudo \
	&& usermod -G developer www-data \
	&& usermod -a -G www-data developer \
	&& mkdir -p /root/.ssh \
	&& echo "Host github.com\n\tStrictHostKeyChecking no\nHost bitbucket.org\n\tStrictHostKeyChecking no" >> /root/.ssh/config \
	&& mkdir -p /etc/ssl/certs \
	&& mkdir -p /etc/ssl/private \
	&& cp /usr/local/pckg-utils/external/apache-selfsigned.crt /etc/ssl/certs/apache-selfsigned.crt \
	&& cp /usr/local/pckg-utils/external/apache-selfsigned.key /etc/ssl/private/apache-selfsigned.key \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /usr/local/pckg-utils
WORKDIR /var/www/html/
COPY docker-entrypoint.sh /
ENTRYPOINT ["sh", "/docker-entrypoint.sh"]