FROM schtr4jh/pckg:base-alpine
MAINTAINER schtr4jh@schtr4jh.net
COPY utils /usr/local/pckg-utils/
RUN sudo apk update \
	&& sudo apk add lsyncd redis-server rabbitmq-server mysql-server \
	&& apk add --repository http://dl-cdn.alpinelinux.org/alpine/edge/community \
	&& date \
	&& sudo apk update \
	&& apk add apache2 libapache2-mod-php php7.4 php7.4-curl php7.4-intl php7.4-xml php7.4-mbstring php7.4-zip php7.4-mysql php7.4-cli php-amqplib php-ssh2 php7.4-zmq php7.4-imap php7.4-redis php7.4-bcmath php7.4-gd php7.4-bz2 php7.4-soap wget xvfb git zip unzip mysql-client \
	&& cp /usr/local/pckg-utils/external/etc_apache2_apache2.conf /etc/apache2/apache2.conf \
	&& cp /usr/local/pckg-utils/external/000-default.conf /etc/apache2/sites-enabled/000-default.conf \
	&& mkdir -p /etc/ssl/private/ \
	&& cp /usr/local/pckg-utils/external/apache-selfsigned.crt /etc/ssl/certs/apache-selfsigned.crt \
	&& cp /usr/local/pckg-utils/external/apache-selfsigned.key /etc/ssl/private/apache-selfsigned.key \
	&& a2enmod expires headers rewrite ssl \
	&& sh /usr/local/pckg-utils/installComposer.sh \
	&& sh /usr/local/pckg-utils/installBasicFrontend.sh \
	&& sudo apk update \
	&& apk add iputils-ping nano net-tools zsh openvpn gcc g++ make build-essential \
	&& wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh || true \
	&& sh /usr/local/pckg-utils/addDeveloper.sh \
	&& mkdir -p /root/.ssh \
	&& echo "Host github.com\n\tStrictHostKeyChecking no\nHost bitbucket.org\n\tStrictHostKeyChecking no" >> /root/.ssh/config \
	&& sh /usr/local/pckg-utils/copyCertificates.sh \
	&& curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - \
	&& sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
	&& sudo apk update && sudo apk add docker-ce docker-ce-cli containerd.io \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /usr/local/pckg-utils
WORKDIR /var/www/html/
COPY docker-entrypoint.sh /
ENTRYPOINT ["sh", "/docker-entrypoint.sh"]