FROM schtr4jh/pckg:php-go-alpine
MAINTAINER schtr4jh@schtr4jh.net
COPY utils /usr/local/pckg-utils/
RUN curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - \
	&& apk update \
	&& apk add nodejs libgbm-dev libpangocairo-1.0-0 libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxi6 libxtst6 libnss3 libcups2 libxss1 libxrandr2 libasound2 libatk1.0-0 libgtk-3-0 \
	&& npm install -g npm@6 \
	&& wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
	&& sudo apt install -y ./google-chrome-stable_current_amd64.deb \
	&& rm google-chrome-stable_current_amd64.deb \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /usr/local/pckg-utils
WORKDIR /var/www/html/
COPY docker-entrypoint-php-go-puppeteer.sh /
ENTRYPOINT ["sh", "/docker-entrypoint-php-go-puppeteer.sh"]