version: '3.8'

services:

  redis:
    image: redis:7-alpine
    env_file: ../env/.env.redis.docker
    command: [ "sh", "-c", "redis-server --requirepass $${REDIS_PASS}" ]
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      VOLUME_CACHE: ${VOLUME_CACHE?:err}
    volumes:

      - "${VOLUME_CACHE}:/data"

x-impero:
  provides:
    redis-config:
      env_file: ../env/.env.redis.provided
