name: Pckg Docker Images CI

on:
  workflow_dispatch:
    branches: [ master ]

jobs:

  build-base:
    name: Build base
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: true
      matrix:
        php-versions: [ '7.4' ]
    steps:

      - uses: actions/checkout@v2

      #- uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Build
        run: "cd full && docker build -t registry.hub.docker.com/schtr4jh/pckg:base -f Dockerfile-base-build ."

      - name: Dump DO Registry auth
        env:
          DOCKER_HUB_AUTH_TOKEN: ${{ secrets.DOCKER_HUB_AUTH_TOKEN }}
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        run: echo $DOCKER_HUB_AUTH_TOKEN | docker login registry.hub.docker.com --username $DOCKER_HUB_USER --password-stdin

      - name: Push
        run: "docker push registry.hub.docker.com/schtr4jh/pckg:base"

  build-apache:
    name: Build Apache
    needs: [ build-base ]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: true
      matrix:
        php-versions: [ '7.4' ]
    steps:

      - uses: actions/checkout@v2

      #- uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Build
        run: "cd full && docker build -t registry.hub.docker.com/schtr4jh/pckg:apache-alpine -f Dockerfile-apache-build ."

      - name: Dump DO Registry auth
        env:
          DOCKER_HUB_AUTH_TOKEN: ${{ secrets.DOCKER_HUB_AUTH_TOKEN }}
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        run: echo $DOCKER_HUB_AUTH_TOKEN | docker login registry.hub.docker.com --username $DOCKER_HUB_USER --password-stdin

      - name: Push
        run: "docker push registry.hub.docker.com/schtr4jh/pckg:apache-alpine"

  build-apache-fpm:
    name: Build Apache FPM
    needs: [ build-base ]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: true
      matrix:
        php-versions: [ '7.4' ]
    steps:

      - uses: actions/checkout@v2

      #- uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Build
        run: "cd full && docker build -t registry.hub.docker.com/schtr4jh/pckg:apache-fpm-alpine -f Dockerfile-apache-fpm-build ."

      - name: Dump DO Registry auth
        env:
          DOCKER_HUB_AUTH_TOKEN: ${{ secrets.DOCKER_HUB_AUTH_TOKEN }}
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        run: echo $DOCKER_HUB_AUTH_TOKEN | docker login registry.hub.docker.com --username $DOCKER_HUB_USER --password-stdin

      - name: Push
        run: "docker push registry.hub.docker.com/schtr4jh/pckg:apache-fpm-alpine"

  build-beanstalkd:
    name: Build Beanstalkd
    needs: [ build-base ]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: true
      matrix:
        php-versions: [ '7.4' ]
    steps:

      - uses: actions/checkout@v2

      #- uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Build
        run: "cd full && docker build -t registry.hub.docker.com/schtr4jh/pckg:beanstalkd-alpine -f Dockerfile-beanstalkd-build ."

      - name: Dump DO Registry auth
        env:
          DOCKER_HUB_AUTH_TOKEN: ${{ secrets.DOCKER_HUB_AUTH_TOKEN }}
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        run: echo $DOCKER_HUB_AUTH_TOKEN | docker login registry.hub.docker.com --username $DOCKER_HUB_USER --password-stdin

      - name: Push
        run: "docker push registry.hub.docker.com/schtr4jh/pckg:beanstalkd-alpine"

#  build-rabbitmq:
#    name: Build RabbitMQ
#    needs: [ build-base ]
#    runs-on: ubuntu-latest
#    timeout-minutes: 20
#    strategy:
#      fail-fast: true
#      matrix:
#        php-versions: [ '7.4' ]
#    steps:
#
#      - uses: actions/checkout@v2
#
#      #- uses: satackey/action-docker-layer-caching@v0.0.11
#
#      - name: Build
#        run: "cd full && docker build -t registry.hub.docker.com/schtr4jh/pckg:rabbitmq-alpine -f Dockerfile-rabbitmq-build ."
#
#      - name: Dump DO Registry auth
#        env:
#          DOCKER_HUB_AUTH_TOKEN: ${{ secrets.DOCKER_HUB_AUTH_TOKEN }}
#          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
#        run: echo $DOCKER_HUB_AUTH_TOKEN | docker login registry.hub.docker.com --username $DOCKER_HUB_USER --password-stdin
#
#      - name: Push
#        run: "docker push registry.hub.docker.com/schtr4jh/pckg:rabbitmq-alpine"

#  build-redis:
#    name: Build Redis
#    needs: [ build-base ]
#    runs-on: ubuntu-latest
#    timeout-minutes: 20
#    strategy:
#      fail-fast: true
#      matrix:
#        php-versions: [ '7.4' ]
#    steps:
#
#      - uses: actions/checkout@v2
#
#      #- uses: satackey/action-docker-layer-caching@v0.0.11
#
#      - name: Build
#        run: "cd full && docker build -t registry.hub.docker.com/schtr4jh/pckg:redis-alpine -f Dockerfile-redis-build ."
#
#      - name: Dump DO Registry auth
#        env:
#          DOCKER_HUB_AUTH_TOKEN: ${{ secrets.DOCKER_HUB_AUTH_TOKEN }}
#          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
#        run: echo $DOCKER_HUB_AUTH_TOKEN | docker login registry.hub.docker.com --username $DOCKER_HUB_USER --password-stdin
#
#      - name: Push
#        run: "docker push registry.hub.docker.com/schtr4jh/pckg:redis-alpine"

  build-sendmail:
    name: Build Sendmail
    needs: [ build-base ]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: true
      matrix:
        php-versions: [ '7.4' ]
    steps:

      - uses: actions/checkout@v2

      #- uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Build
        run: "cd full && docker build -t registry.hub.docker.com/schtr4jh/pckg:sendmail-php -f Dockerfile-sendmail-php-build ."

      - name: Dump DO Registry auth
        env:
          DOCKER_HUB_AUTH_TOKEN: ${{ secrets.DOCKER_HUB_AUTH_TOKEN }}
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        run: echo $DOCKER_HUB_AUTH_TOKEN | docker login registry.hub.docker.com --username $DOCKER_HUB_USER --password-stdin

      - name: Push
        run: "docker push registry.hub.docker.com/schtr4jh/pckg:sendmail-php"

  build-php:
    name: Build PHP
    needs: [ build-base ]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: true
      matrix:
        php-versions: [ '7.4' ]
    steps:

      - uses: actions/checkout@v2

      #- uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Build
        run: "cd full && docker build -t registry.hub.docker.com/schtr4jh/pckg:php-cron -f Dockerfile-php-cron-build ."

      - name: Dump DO Registry auth
        env:
          DOCKER_HUB_AUTH_TOKEN: ${{ secrets.DOCKER_HUB_AUTH_TOKEN }}
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        run: echo $DOCKER_HUB_AUTH_TOKEN | docker login registry.hub.docker.com --username $DOCKER_HUB_USER --password-stdin

      - name: Push
        run: "docker push registry.hub.docker.com/schtr4jh/pckg:php-cron"

  build-go:
    name: Build PHP Go
    needs: [ build-base ]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: true
      matrix:
        php-versions: [ '7.4' ]
    steps:

      - uses: actions/checkout@v2

      #- uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Build
        run: "cd full && docker build -t registry.hub.docker.com/schtr4jh/pckg:php-go-alpine -f Dockerfile-php-go-build ."

      - name: Dump DO Registry auth
        env:
          DOCKER_HUB_AUTH_TOKEN: ${{ secrets.DOCKER_HUB_AUTH_TOKEN }}
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        run: echo $DOCKER_HUB_AUTH_TOKEN | docker login registry.hub.docker.com --username $DOCKER_HUB_USER --password-stdin

      - name: Push
        run: "docker push registry.hub.docker.com/schtr4jh/pckg:php-go-alpine"

  build-go-supervisor:
    name: Build PHP Go Supervisor
    needs: [ build-base ]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: true
      matrix:
        php-versions: [ '7.4' ]
    steps:

      - uses: actions/checkout@v2

      #- uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Build
        run: "cd full && docker pull schtr4jh/pckg:php-go-alpine && docker build -t registry.hub.docker.com/schtr4jh/pckg:php-go-supervisord-alpine -f Dockerfile-php-go-supervisord-build ."

      - name: Dump DO Registry auth
        env:
          DOCKER_HUB_AUTH_TOKEN: ${{ secrets.DOCKER_HUB_AUTH_TOKEN }}
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        run: echo $DOCKER_HUB_AUTH_TOKEN | docker login registry.hub.docker.com --username $DOCKER_HUB_USER --password-stdin

      - name: Push
        run: "docker push registry.hub.docker.com/schtr4jh/pckg:php-go-supervisord-alpine"

  build-latest:
    name: Build latest (dev)
    needs: [ build-base ]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: true
      matrix:
        php-versions: [ '7.4' ]
    steps:

      - uses: actions/checkout@v2

      #- uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Build
        run: "cd full && docker build -t registry.hub.docker.com/schtr4jh/pckg:latest -f Dockerfile-build ."

      - name: Dump DO Registry auth
        env:
          DOCKER_HUB_AUTH_TOKEN: ${{ secrets.DOCKER_HUB_AUTH_TOKEN }}
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        run: echo $DOCKER_HUB_AUTH_TOKEN | docker login registry.hub.docker.com --username $DOCKER_HUB_USER --password-stdin

      - name: Push
        run: "docker push registry.hub.docker.com/schtr4jh/pckg:latest"
