name: Pckg Docker Images CI

on:
  workflow_dispatch:
    branches: [ master ]

jobs:

  build-base:
    name: Build base
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: true
      matrix:
        php-versions: [ '7.4' ]
    env:
      IMAGE_TAG: registry.hub.docker.com/schtr4jh/pckg:base
    steps:

      - uses: actions/checkout@v2

      #- uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Build
        run: "cd full && docker build -t $IMAGE_TAG -f Dockerfile-base-build ."

      - name: Dump DO Registry auth
        env:
          DOCKER_HUB_AUTH_TOKEN: ${{ secrets.DOCKER_HUB_AUTH_TOKEN }}
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        run: echo $DOCKER_HUB_AUTH_TOKEN | docker login registry.hub.docker.com --username $DOCKER_HUB_USER --password-stdin

      - name: Push
        run: "docker push $IMAGE_TAG"

  build-apache:
    name: Build Apache
    needs: [ build-base ]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: true
      matrix:
        php-versions: [ '7.4' ]
    env:
      IMAGE_TAG: registry.hub.docker.com/schtr4jh/pckg:apache-alpine
    steps:

      - uses: actions/checkout@v2

      #- uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Build
        run: "cd full && docker build -t $IMAGE_TAG -f Dockerfile-apache-build ."

      - name: Test
        run: "cd full && bash test-build-image.sh $IMAGE_TAG apache-alpine -alpine¸"

      - name: Dump DO Registry auth
        env:
          DOCKER_HUB_AUTH_TOKEN: ${{ secrets.DOCKER_HUB_AUTH_TOKEN }}
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        run: echo $DOCKER_HUB_AUTH_TOKEN | docker login registry.hub.docker.com --username $DOCKER_HUB_USER --password-stdin

      - name: Push
        run: "docker push $IMAGE_TAG"

  build-apache-fpm:
    name: Build Apache FPM
    needs: [ build-base ]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: true
      matrix:
        php-versions: [ '7.4' ]
    env:
      IMAGE_TAG: registry.hub.docker.com/schtr4jh/pckg:apache-fpm-alpine
    steps:

      - uses: actions/checkout@v2

      #- uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Build
        run: "cd full && docker build -t $IMAGE_TAG -f Dockerfile-apache-fpm-build ."

      - name: Test
        run: "cd full && bash test-build-image.sh $IMAGE_TAG apache-fpm-alpine -apache-fpm"

      - name: Dump DO Registry auth
        env:
          DOCKER_HUB_AUTH_TOKEN: ${{ secrets.DOCKER_HUB_AUTH_TOKEN }}
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        run: echo $DOCKER_HUB_AUTH_TOKEN | docker login registry.hub.docker.com --username $DOCKER_HUB_USER --password-stdin

      - name: Push
        run: "docker push $IMAGE_TAG"

  build-apache-fpm-snappy:
    name: Build Apache FPM Snappy
    needs: [ build-base ]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: true
      matrix:
        php-versions: [ '7.4' ]
    env:
      IMAGE_TAG: registry.hub.docker.com/schtr4jh/pckg:apache-fpm-alpine-snappy
    steps:

      - uses: actions/checkout@v2

      #- uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Build
        run: "cd full && docker build -t $IMAGE_TAG -f Dockerfile-apache-fpm-snappy-build ."

      - name: Test
        run: "cd full && bash test-build-image.sh $IMAGE_TAG apache-fpm-alpine -apache-fpm"

      - name: Dump DO Registry auth
        env:
          DOCKER_HUB_AUTH_TOKEN: ${{ secrets.DOCKER_HUB_AUTH_TOKEN }}
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        run: echo $DOCKER_HUB_AUTH_TOKEN | docker login registry.hub.docker.com --username $DOCKER_HUB_USER --password-stdin

      - name: Push
        run: "docker push $IMAGE_TAG"

  build-beanstalkd:
    name: Build Beanstalkd
    needs: [ build-base ]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: true
      matrix:
        php-versions: [ '7.4' ]
    env:
      IMAGE_TAG: registry.hub.docker.com/schtr4jh/pckg:beanstalkd-alpine
    steps:

      - uses: actions/checkout@v2

      #- uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Build
        run: "cd full && docker build -t $IMAGE_TAG -f Dockerfile-beanstalkd-build ."

      - name: Test
        run: "cd full && bash test-build-image.sh $IMAGE_TAG beanstalkd-alpine -beanstalkd"

      - name: Dump DO Registry auth
        env:
          DOCKER_HUB_AUTH_TOKEN: ${{ secrets.DOCKER_HUB_AUTH_TOKEN }}
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        run: echo $DOCKER_HUB_AUTH_TOKEN | docker login registry.hub.docker.com --username $DOCKER_HUB_USER --password-stdin

      - name: Push
        run: "docker push $IMAGE_TAG"

#  build-rabbitmq:
#    name: Build RabbitMQ
#    needs: [ build-base ]
#    runs-on: ubuntu-latest
#    timeout-minutes: 20
#    strategy:
#      fail-fast: true
#      matrix:
#        php-versions: [ '7.4' ]
#    steps:
#
#      - uses: actions/checkout@v2
#
#      #- uses: satackey/action-docker-layer-caching@v0.0.11
#
#      - name: Build
#        run: "cd full && docker build -t registry.hub.docker.com/schtr4jh/pckg:rabbitmq-alpine -f Dockerfile-rabbitmq-build ."
#
#      - name: Dump DO Registry auth
#        env:
#          DOCKER_HUB_AUTH_TOKEN: ${{ secrets.DOCKER_HUB_AUTH_TOKEN }}
#          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
#        run: echo $DOCKER_HUB_AUTH_TOKEN | docker login registry.hub.docker.com --username $DOCKER_HUB_USER --password-stdin
#
#      - name: Push
#        run: "docker push registry.hub.docker.com/schtr4jh/pckg:rabbitmq-alpine"

#  build-redis:
#    name: Build Redis
#    needs: [ build-base ]
#    runs-on: ubuntu-latest
#    timeout-minutes: 20
#    strategy:
#      fail-fast: true
#      matrix:
#        php-versions: [ '7.4' ]
#    steps:
#
#      - uses: actions/checkout@v2
#
#      #- uses: satackey/action-docker-layer-caching@v0.0.11
#
#      - name: Build
#        run: "cd full && docker build -t registry.hub.docker.com/schtr4jh/pckg:redis-alpine -f Dockerfile-redis-build ."
#
#      - name: Dump DO Registry auth
#        env:
#          DOCKER_HUB_AUTH_TOKEN: ${{ secrets.DOCKER_HUB_AUTH_TOKEN }}
#          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
#        run: echo $DOCKER_HUB_AUTH_TOKEN | docker login registry.hub.docker.com --username $DOCKER_HUB_USER --password-stdin
#
#      - name: Push
#        run: "docker push registry.hub.docker.com/schtr4jh/pckg:redis-alpine"

  build-sendmail:
    name: Build Sendmail
    needs: [ build-base ]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: true
      matrix:
        php-versions: [ '7.4' ]
    env:
      IMAGE_TAG: registry.hub.docker.com/schtr4jh/pckg:sendmail-php
    steps:

      - uses: actions/checkout@v2

      #- uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Build
        run: "cd full && docker build -t $IMAGE_TAG -f Dockerfile-sendmail-php-build ."

      - name: Test
        run: "cd full && bash test-build-image.sh $IMAGE_TAG sendmail-php -sendmail-php"

      - name: Dump DO Registry auth
        env:
          DOCKER_HUB_AUTH_TOKEN: ${{ secrets.DOCKER_HUB_AUTH_TOKEN }}
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        run: echo $DOCKER_HUB_AUTH_TOKEN | docker login registry.hub.docker.com --username $DOCKER_HUB_USER --password-stdin

      - name: Push
        run: "docker push $IMAGE_TAG"

  build-php:
    name: Build PHP
    needs: [ build-base ]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: true
      matrix:
        php-versions: [ '7.4' ]
    env:
      IMAGE_TAG: registry.hub.docker.com/schtr4jh/pckg:php-cron
    steps:

      - uses: actions/checkout@v2

      #- uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Build
        run: "cd full && docker build -t $IMAGE_TAG -f Dockerfile-php-cron-build ."

      - name: Test
        run: "cd full && bash test-build-image.sh $IMAGE_TAG php-cron -php-cron"

      - name: Dump DO Registry auth
        env:
          DOCKER_HUB_AUTH_TOKEN: ${{ secrets.DOCKER_HUB_AUTH_TOKEN }}
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        run: echo $DOCKER_HUB_AUTH_TOKEN | docker login registry.hub.docker.com --username $DOCKER_HUB_USER --password-stdin

      - name: Push
        run: "docker push $IMAGE_TAG"

  build-go:
    name: Build PHP Go
    needs: [ build-base ]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: true
      matrix:
        php-versions: [ '7.4' ]
    env:
      IMAGE_TAG: registry.hub.docker.com/schtr4jh/pckg:php-go-alpine
    steps:

      - uses: actions/checkout@v2

      #- uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Build
        run: "cd full && docker build -t $IMAGE_TAG -f Dockerfile-php-go-build ."

      - name: Test
        run: "cd full && bash test-build-image.sh $IMAGE_TAG php-go-alpine -php-go"

      - name: Dump DO Registry auth
        env:
          DOCKER_HUB_AUTH_TOKEN: ${{ secrets.DOCKER_HUB_AUTH_TOKEN }}
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        run: echo $DOCKER_HUB_AUTH_TOKEN | docker login registry.hub.docker.com --username $DOCKER_HUB_USER --password-stdin

      - name: Push
        run: "docker push $IMAGE_TAG"

  build-go-supervisor:
    name: Build PHP Go Supervisor
    needs: [ build-base ]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: true
      matrix:
        php-versions: [ '7.4' ]
    env:
      IMAGE_TAG: registry.hub.docker.com/schtr4jh/pckg:php-go-supervisord-alpine
    steps:

      - uses: actions/checkout@v2

      #- uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Build
        run: "cd full && docker pull schtr4jh/pckg:php-go-alpine && docker build -t $IMAGE_TAG -f Dockerfile-php-go-supervisord-build ."

      - name: Test
        run: "cd full && bash test-build-image.sh $IMAGE_TAG php-go-supervisord-alpine -php-go-supervisord"

      - name: Dump DO Registry auth
        env:
          DOCKER_HUB_AUTH_TOKEN: ${{ secrets.DOCKER_HUB_AUTH_TOKEN }}
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        run: echo $DOCKER_HUB_AUTH_TOKEN | docker login registry.hub.docker.com --username $DOCKER_HUB_USER --password-stdin

      - name: Push
        run: "docker push $IMAGE_TAG"

  build-latest:
    name: Build latest (dev)
    needs: [ build-base ]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: true
      matrix:
        php-versions: [ '7.4' ]
    env:
      IMAGE_TAG: registry.hub.docker.com/schtr4jh/pckg:latest
    steps:

      - uses: actions/checkout@v2

      #- uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Build
        run: "cd full && docker build -t $IMAGE_TAG -f Dockerfile-build ."

      - name: Test
        run: "cd full && bash test-build-image.sh $IMAGE_TAG latest \"\""

      - name: Dump DO Registry auth
        env:
          DOCKER_HUB_AUTH_TOKEN: ${{ secrets.DOCKER_HUB_AUTH_TOKEN }}
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        run: echo $DOCKER_HUB_AUTH_TOKEN | docker login registry.hub.docker.com --username $DOCKER_HUB_USER --password-stdin

      - name: Push
        run: "docker push $IMAGE_TAG"

  build-services:
    name: Build services (dev)
    needs: [ build-base ]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: true
      matrix:
        php-versions: [ '7.4' ]
    env:
      IMAGE_TAG: registry.hub.docker.com/schtr4jh/pckg:services
    steps:

      - uses: actions/checkout@v2

      #- uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Build
        run: "cd full && docker build -t $IMAGE_TAG -f Dockerfile-services-build ."

      - name: Test
        run: "cd full && bash test-build-image.sh $IMAGE_TAG services"

      - name: Dump DO Registry auth
        env:
          DOCKER_HUB_AUTH_TOKEN: ${{ secrets.DOCKER_HUB_AUTH_TOKEN }}
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        run: echo $DOCKER_HUB_AUTH_TOKEN | docker login registry.hub.docker.com --username $DOCKER_HUB_USER --password-stdin

      - name: Push
        run: "docker push $IMAGE_TAG"
